import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  botaoVoltar: {
    padding: 10,
    backgroundColor: '#ffd700',
    alignSelf: 'flex-start',
    margin: 10,
    borderRadius: 6,
  },
  textoVoltar: { color: '#160b30', fontWeight: 'bold' },
  acoes: { flexDirection: 'row', gap: 10, paddingHorizontal: 10, marginBottom: 10 },
  botaoAcao: { backgroundColor: '#160b30', padding: 10, borderRadius: 6 },
  textoBotaoAcao: { color: '#fff', fontWeight: 'bold' },
  secao: { marginBottom: 20, paddingHorizontal: 10 },
  tituloSecao: {
    backgroundColor: '#160b30',
    color: '#fff',
    padding: 5,
    marginBottom: 10,
    fontWeight: 'bold',
  },
  linhaProdutos: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  cardProduto: {
    backgroundColor: '#ffd700',
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
  },
  textoProduto: {
    color: '#160b30',
    fontWeight: 'bold',
  },
  overlayModal: {
    flex: 1,
    backgroundColor: '#000000aa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderColor: '#160b30',
    borderWidth: 1,
    width: '80%',
    padding: 20,
    gap: 12,
    position: 'relative',
    borderRadius: 8,
  },
  tituloModal: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#160b30',
  },
  linhaModal: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  input: {
    backgroundColor: '#f0f0f0',
    padding: 10,
    flex: 1,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#160b30',
    color: '#160b30',
  },
  caixaFoto: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  botaoAdicionar: {
    backgroundColor: '#ffd700',
    padding: 12,
    alignItems: 'center',
    borderRadius: 6,
  },
  textoAdicionar: {
    color: '#160b30',
    fontWeight: 'bold',
  },
  botaoFechar: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 1,
    backgroundColor: '#f0f0f0',
    borderRadius: 20,
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#160b30',
  },
  textoFechar: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#160b30',
  },
});
